/*
 * This file is generated by jOOQ.
*/
package de.rieckpil.learning.springbootjooqexample.domain;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.comments_id_seq</code>
     */
    public static final Sequence<Long> COMMENTS_ID_SEQ = new SequenceImpl<Long>("comments_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.posts_id_seq</code>
     */
    public static final Sequence<Long> POSTS_ID_SEQ = new SequenceImpl<Long>("posts_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
