DROP TABLE IF EXISTS POSTS CASCADE;

CREATE TABLE POSTS (
  ID BIGSERIAL NOT NULL ,
  TITLE varchar(200) NOT NULL,
  CONTENT varchar(255) DEFAULT NULL,
  CREATED_ON int8 DEFAULT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS COMMENTS CASCADE;

CREATE TABLE COMMENTS (
  ID BIGSERIAL NOT NULL ,
  POST_ID int8 NOT NULL,
  NAME int8 NOT NULL,
  EMAIL int8 NOT NULL,
  CONTENT varchar(255) DEFAULT NULL,
  CREATED_ON int8 DEFAULT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (POST_ID) REFERENCES POSTS(ID)
);

