package com.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.Arrays;

import javax.sql.DataSource;

import com.zaxxer.hikari.HikariDataSource;
import net.ttddyy.dsproxy.support.ProxyDataSourceBuilder;

public class Application {

  public static void main(String[] args) throws SQLException {
    DataSource ds = createDataSource();
    try (Connection connection = ds.getConnection()) {
      System.out.println("connection.isValid(0) = " + connection.isValid(0));

      try (PreparedStatement stmt = connection.prepareStatement("insert into" +
          " users (first_name, last_name, registration_date) " +
          "values (?,?,?)"
        , Statement.RETURN_GENERATED_KEYS)) {
        // basicInsert(stmt);
        // batchInsert(stmt);
      }

      try (PreparedStatement stmt = connection.prepareStatement("select * from users")) {
        ResultSet resultSet = stmt.executeQuery();
        while (resultSet.next()) {
          int id = resultSet.getInt("id");
          String firstName = resultSet.getString("first_name");
          String lastName = resultSet.getString("last_name");
          LocalDateTime registrationDate = resultSet.getObject(
            "registration_date", LocalDateTime.class);
          System.out.println("Found user: " + id + " | " + firstName + " | " + lastName + " | " + registrationDate);
        }
      }
    }
  }

  private static void batchInsert(PreparedStatement stmt) throws SQLException {
    stmt.setString(1, "[Some FirstName]");
    stmt.setString(2, "[Some LastName]");
    stmt.setObject(3, LocalDateTime.now());

    stmt.addBatch();

    stmt.setString(1, "[Some Other FirstName]");
    stmt.setString(2, "[Some Other LastName]");
    stmt.setObject(3, LocalDateTime.now());

    stmt.addBatch();

    final int[] insertCounts = stmt.executeBatch();
    System.out.println("I inserted " + Arrays.toString(insertCounts) + "rows");
  }

  private static void basicInsert(PreparedStatement stmt) throws SQLException {
    stmt.setString(1, "[Some FirstName]");
    stmt.setString(2, "[Some LastName]");
    stmt.setObject(3, LocalDateTime.now());
    int insertedRows = stmt.executeUpdate();
    final ResultSet keysResultSet = stmt.getGeneratedKeys();
    keysResultSet.next();
    final long autogenerateId = keysResultSet.getLong(1);
    System.out.println("Inserted [" + insertedRows + "] row into table" +
      " users, with autogenerated id [" + autogenerateId + "]");
  }

  private static DataSource createDataSource() {
    HikariDataSource ds = new HikariDataSource();
    ds.setJdbcUrl("jdbc:h2:~/Desktop/junk;INIT=RUNSCRIPT FROM 'classpath:schema.sql'");
    ds.setUsername("sa");
    ds.setPassword("s3cr3tPassword");

    DataSource dataSource =
      ProxyDataSourceBuilder.create(ds) // pass original datasource
        .logQueryToSysOut()
        .build();
    return dataSource;
  }
}
