CREATE TABLE Address(
  id bigint generated by default as identity,
  city varchar(255),
  house_number integer not null,
  street varchar(255),
  person_id bigint,
  primary key (id)
);

CREATE TABLE Passport(
  id bigint generated by default as identity,
  passport_id varchar(255),
  primary key (id)
);

CREATE TABLE Person(
  id bigint generated by default as identity,
  first_name varchar(255),
  last_name varchar(255),
  passport_id bigint not null,
  primary key (id)
);

alter table address add constraint FK81ihijcn1kdfwffke0c0sjqeb foreign key (person_id) references person;
alter table person add constraint FKpm70pbnghc1m7eq6n4jf5fkd foreign key (passport_id) references passport;